# Generated by Django 4.0 on 2021-12-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForeCastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_text', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=3)),
                ('humidity', models.CharField(max_length=3)),
                ('icon', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
