name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SSH into production server & pull latest codebase
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.VPSDIME_HOST }}
          USERNAME: ${{ secrets.VPSDIME_USERNAME }}
          PORT: ${{ secrets.VPSDIME_PORT }}
          KEY: ${{ secrets.VPSDIME_SSHKEY }}
          script: |
            cd weatherapp
            git checkout .
            git pull

#      - name: Checkout Frontend code
#        uses: actions/checkout@v2

      - name: Prepare Frontend
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Build frontend
        working-directory: ./frontend
        run: |
            npm i
            npm run build

#      - name: Checkout Backend code
#        uses: actions/checkout@v2
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --no-input
#          touch ./logs/gunicorn.log
#          touch ./logs/gunicorn-access.log


#  deploy:
#    needs: [build]
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Copy repository contents via scp
#        uses: appleboy/scp-action@master
#        env:
#          HOST: ${{ secrets.VPSDIME_HOST }}
#          USERNAME: ${{ secrets.VPSDIME_USERNAME }}
#          PORT: ${{ secrets.VPSDIME_PORT }}
#          KEY: ${{ secrets.VPSDIME_SSHKEY }}
#        with:
#          source: "."
#          target: "/var/www/mywebsite"

#      - name: SSH into production server
#        uses: appleboy/ssh-action@master
#        with:
#          HOST: ${{ secrets.VPSDIME_HOST }}
#          USERNAME: ${{ secrets.VPSDIME_USERNAME }}
#          PORT: ${{ secrets.VPSDIME_PORT }}
#          KEY: ${{ secrets.VPSDIME_SSHKEY }}
#          script: ls

        # - name: Deploy to EB
        #   uses: einaregilsson/beanstalk-deploy@v20
        #   with:
        #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     application_name: django-github-action-aws
        #     environment_name: Djangogithubactionaws-env
        #     version_label: 12350
        #     region: "us-east-1"
        #     deployment_package: deploy.zip
        #     use_existing_version_if_available: true

      # - name: Checkout source code
      #   uses: actions/checkout@v2

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: django-github-action-aws
      #     environment_name: Djangogithubactionaws-env
      #     version_label: 12350
      #     region: "us-east-1"
      #     deployment_package: deploy.zip
